### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by TiesToetToet** [dheerajrp/Download-FRIENDS-all-seasons#1]
It does not work for me. I downloaded the files as .gz files but now i am stuck. What should i do?

**Comment by TiesToetToet** [comment]
I also downloaded the .src files but it still wont work

**Comment by dheerajrp** [comment]
@TiesToetToet can you please what error you are getting? Is that related to the driver version?

**Comment by TiesToetToet** [comment]
I dont get an error, i just dont know how to run everything

**Comment by dheerajrp** [comment]
Hi @TiesToetToet 
will update you soon regarding the run. The repo is still under develpment. I will let you know once done. Thanks

**Comment by dheerajrp** [comment]
You can check some other repositories of mine if you find any of them useful.
